version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cli
    versions:
    - 3.13.2
    - 3.19.1
    - 3.20.0
    - 3.20.1
    - 3.21.13
    - 3.21.2
    - 3.21.3
    - 3.21.5
    - 3.22.0
    - 3.23.1
    - 3.23.2
    - 3.23.3
    - 3.24.0
  - dependency-name: webpack
    versions:
    - 5.28.0
    - 5.35.1
  - dependency-name: "@dsmjs/babel-preset"
    versions:
    - 1.0.59
    - 1.0.60
    - 1.0.61
    - 1.0.62
    - 1.0.63
    - 1.0.64
    - 1.0.65
    - 1.0.66
  - dependency-name: "@dsmjs/eslint-config-react"
    versions:
    - 1.1.54
    - 1.1.55
    - 1.1.56
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.0
  - dependency-name: react-use
    versions:
    - 17.0.0
  - dependency-name: "@emotion/babel-preset-css-prop"
    versions:
    - 11.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
