language: node_js
dist: trusty
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
after_install: npm ls >/dev/null
before_script: npm run greenkeeper:update-lockfile
before_deploy:
- npm run build-storybook
- git config --global user.email "$GIT_EMAIL"
- git config --global user.name "dsmJS Bot"
deploy:
- skip_cleanup: true
  provider: script
  script: npm run deploy
after_success:
- npm run coverage:report
- npm run semantic-release
after_script: npm run greenkeeper:upload-lockfile
env:
  global:
  - secure: ogrRqV1ZSVAIGzS9GLhtX7eJDiP9DnsE+rqwIaKpIERY203RwYKD3EoTOAMnZcG1pe6Zcs2JHazflAOECgMdsb1c6xTQayNCC80K/BuqH0T2YMfB6AU5dLQipSKlbHhRafJjx5BIJ7PGAzZZXXSGICPc7rc3/9I0+o5hKFCw5717qDvmK16zTAE4Dbyfeks4aNf+fNFwrQXL1dXEUZHu4gZDvFUwvIHzmWl4GrLqtopwMdKvvWE2b8xKla+Ka1fsO/HmyVe85v+zDVpiC9Nfn5JpuNOfdKMetQRc+B/7jqMY9VO6bI8dYeCzleoHw2K8LZ5k6hgV97xHycqRvbyKHFPxFQAP55yNzg3FHg3ekwv6f3++Og2VJdtdCftwDcuHS/7dFrQ3tsUlz6L8fCr9GG3Ae4CxWMe2Vzr4/S/sVwmVWOD/GSoOCLGuxG8dqvS/7y+r/eOn7MBIRfLB7GxQ39QzY6bPE3+Kl2l+Op0A1sF8K2EM9SgoWBZS3ctVg+DnSP5zSs2p50EF46ST8izcnnb9JMCEhUoavvzhWDTOrzlQhTB+eQayLlbnPdIUDnctrezbpkG7io/7f0p2cwhGXvH2nLUKQH7KYDB0I0h6Oly20c+EbVWxzosDARekjfHRzeygc+7F2aaLerWBEiWWEQtwNUq+y6YHUtR+ZhST86c=
  - secure: tDK87TTNV9sR/YI0M1cNNK3PReA+29e4+PybjIG6eTQDxOMj/GNMfGywiAUD7N0mgFUlPsMQ4iMvo0xNTNLvSs/ecKMOKgQvhakuSp4BLLSxNk1c0qqRQxAJendCVQulr/ySGQDOYqHepaoW3qaD5KOuoW3gqeBpmsMYT9SO4b8uJR5DPiFRyRBJ+wwFIHT/NnAZxulF5viQDciV9cgyeGnLtRQ3f23BezaONout/i6DN7QjzKzrd0BZ3CNqGAzAKGFrSKvomCc6pHZuvwC/2XyKGCdEV86rxsmODqlcbymkzyN+o1jkJbZ0nwXFBENV6aySFS4sEpmei8s0v71jMyfcQv3R8pms0CKJadHwx1VMOM+6Nh7Pz3vBF/rfk46tCBkq+6ouLufdD3/PQTkw6DU2K+TZOMuzVZxTEF6y+waxBJoOem8Q5afZVRMaLMhhtRwZVfHiw9L/t2IAy3mPEOdVAJB9iLCVQp1MIbEuVzN08cwTXzND8SNIyuPaMVcsSvj4gHNg94VF92Nn6WjbaqapA+SVt5KEuT96R0rGzbwm71M3Y90jfZgoMfFhUSPGWksMqRFLK9qr5tIPc9NCiU/PbEcVeeMviyM+zuYV+UJKCBsC3rdWNoeNq17lq31nGtNP/U6aKJidKzwLEG4ITQXBaUDnp74RkRymfeJDSfI=
