version: "~> 1.0"
language: node_js
dist: trusty
notifications:
  email: false
import:
- source: dsmjs/.travis-ci:authenticated-semantic-release.yml
- source: dsmjs/.travis-ci:authenticated-netlify-deploy.yml
before_install: curl ifconfig.co
after_install: npm ls >/dev/null
after_success:
- npm run coverage:report
- npm run snapshot
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: dX25+t+eTtzZXfhIcqf9XRKyVmL+lQ4BaaqP6gGD/VOxmtzUflQ44FkBLVu+EN+Kgl683WglVKZT5WcpiePiFTtbidWFmufsXHnOhvgI2EcptC8AP3lazNFtseVx/WNG9ovLPM0YwTfBPEx1kJBhZoez7YqbK0bTNOak7q2oClSeu3o8qEsPlhM3kInnwOht77+H+GPDA//PmYAt+6SMU/vDCJBfIHncL6vOtgD+pFOCJtG5oB1dU5PN5TjAMPnWAhBYqx05Orfcy/RbTBqwul9yODdDuI5vUxblmAsPWlw7zLEpZIzy/MBqZcaJGsskPGiqGLXVzlmWalAyWDhgujcKwUDUzs9ozJqLc3CbCHyb4ULePkHq5D3/9bU52+nju0k6TNubsh8OGhm0d6uJ5GMgkPD+KAtcpYHiB4CzLz7bDDZ/E5pgJ+AYIxm/UHcBXIGa5bUfTC3FxunHXaGWAiIQd+2yT7tIvS4TbC6RkOy1zoJDek4XlJa8xbRmS6IdPJeVV31wW/XLxg8gelLAkX+QUyom031/H5waD/UhniR/1xaOA0mAQ5Eoxs+MfcGlzoxCzY9E7rFubMauJYDx0ln/M9jNHjQ5t6SaxG7RbP7oJagKeKCHTX2KxWZdFMqOBDu/AMJ0iBeuiAixfMgpoC4jxPAxSnlx5ypur/tsPcc=
  - secure: eReXqYlN1EDNt3ehGNtrQgOEBYefTPhmqYDGQxylzDf3DiqHQl93jvWXRWwLSQAy/WJ51eLawPx4dYS2Su2LwOrXD+ZVgg5uCIzkd7I5FnLu3PsU2ygXC/KYDNuuwR7PRHrb1tZF3fSOJnlk++TziQ13wy9CY/OUAZZEp1hUBXuyIIMeXI05gfTYzAP85YBYyQ2NIHQIYE64mdRgJ6ivl5E65o+F/8bnI4dm4vFyYHuuSLWJ2Vez9Nm2kJi0SLwhOWvf7COoUwOtbgZunJLzSGGzaUWdTZ0RVv2jxWQED6X1LYIDP2LHBWIsa5jJXYlyWM+V0EvpE2lLXRB5AtIBvMGrbcrSmoWGYPNVLHidbt/rYVGt7L1QlHCb50g2o9Z0CAKgRUBEiilBK94JVS3T1VMgtZBxtoR0Efvjk8NEK10gYCGf+UTLxI7R7/WuRFwLIcjYqnOMgqs5xzkr0b8NvK2YHENQaj56ZYXW0qdi5jPYAREDKVCgme63BqjCNYa1btbUmJ7E+bAuXTgUCjJA1oFK0FsfeZ/MrfoHymi5bm5pTeQJhWN30L/qRzFDhu0oKPI5FfpS1qD0QHHo6of0tgslK1N7R1ZqAC76oeyUNm9+pUM9LfsX8bwehoVyFCfAe+Ae8799UbVqSiRLn23Zsd59H3R4uJxO/fJ6afoC+as=
